version: 2
jobs:
  build:
    context: bundle
    docker:
      - image: cimg/ruby:2.6.8-browsers
    environment:
      BUNDLER_VERSION: 1.17.2
    working_directory: ~/lucasfcosta.github.io
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install bundler
          command: gem install bundler:$BUNDLER_VERSION
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: build _site
          command: bundle exec jekyll build
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - persist_to_workspace:
          root: ./
          paths:
            - _site

  deploy:
    context: bundle
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/lucasfcosta.github.io
    steps:
      - run:
          name: install awscli
          command: sudo pip install awscli
      - attach_workspace:
          at: _site
      - run:
          name: deploy to S3
          command: aws s3 sync --delete _site/* s3://lucasfcosta

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
